language: c

env:
  global:
    - GCC_BUILD_DIR="build-gcc"

compiler:
  - gcc

os:
  - linux

install:
  - sudo apt-get install libgmp-dev libmpfr-dev libmpc-dev

before_script:
  - git clone --depth 1 https://github.com/thvnx/gcc.git --branch accurate-limited-range
  - mkdir $GCC_BUILD_DIR
  - cd $GCC_BUILD_DIR && ../gcc/configure --disable-multilib && make -j8

script:
  - echo OK
